name: Build and Deploy Vue App

on:
  push:
    branches: [master] # Замените на вашу основную ветку, если она называется иначе

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.4.0' # Укажите версию Node.js, которую вы используете

      - name: Install dependencies
        run: npm ci

      - name: Build Vue app
        run: npm run build

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Check SSH connection
        run: ssh -v github-action@vzhurbenko.dev 'echo "SSH connection successful"'

      - name: Deploy with rsync
        run: |
          rsync -avz --delete ./dist/ github-action@vzhurbenko.dev:/var/www/ttscore.vzhurbenko.dev/

      - name: Verify deployment
        run: ssh github-action@vzhurbenko.dev 'ls -la /var/www/ttscore.vzhurbenko.dev/'
