name: Build and Deploy Vue App

on:
  push:
    branches: [ main ]  # Замените на вашу основную ветку, если она называется иначе

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23.4.0'  # Укажите версию Node.js, которую вы используете

    - name: Install dependencies
      run: npm ci

    - name: Build Vue app
      run: npm run build

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: DEPLOY_KEY
      run: |
        ssh-keyscan -H vzhurbenko.dev >> ~/.ssh/known_hosts
        rsync -avz --delete ./dist/ github-action@vzhurbenko.dev:/var/www/ttscore.vzhurbenko.dev/
